----------- Delete Tables ---------------
DROP TABLE IF EXISTS FILE_DOWNLOAD
DROP TABLE IF EXISTS ARTICLE_TYPE
DROP TABLE IF EXISTS TEMPLATE_NAME
DROP TABLE IF EXISTS TEMPLATE_TYPE
----------- Delete Tables ---------------

----------- Create Tables ---------------
CREATE TABLE TEMPLATE_TYPE (
	ID BIGINT NOT NULL,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	STATUS VARCHAR(10),
	CREATED_BY VARCHAR(20),
	CREATED_DATE DATETIME,
	MODIFIED_BY VARCHAR(20),
	MODIFIED_DATE DATETIME,
	PRIMARY KEY (ID)
);

CREATE TABLE TEMPLATE_NAME (
	ID BIGINT NOT NULL,
	NAME VARCHAR(255),
	ACRONYM VARCHAR(20),
	DESCRIPTION VARCHAR(255),
	STATUS VARCHAR(10),
	CREATED_BY VARCHAR(20),
	CREATED_DATE DATETIME,
	MODIFIED_BY VARCHAR(20),
	MODIFIED_DATE DATETIME,
	TEMPLATE_TYPE_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TEMPLATE_TYPE_ID) REFERENCES TEMPLATE_TYPE(ID)
);

CREATE TABLE ARTICLE_TYPE (
	ID BIGINT NOT NULL,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	STATUS VARCHAR(10),
	CREATED_BY VARCHAR(20),
	CREATED_DATE DATETIME,
	MODIFIED_BY VARCHAR(20),
	MODIFIED_DATE DATETIME,
	TEMPLATE_NAME_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TEMPLATE_NAME_ID) REFERENCES TEMPLATE_NAME(ID)
);

CREATE TABLE FILE_DOWNLOAD (
	ID BIGINT NOT NULL,
	FORMAT VARCHAR(30),
	URL VARCHAR(255),
	DESCRIPTIVE_TEXT VARCHAR(255),
	TEMPLATE_TYPE_ID BIGINT,
	TEMPLATE_NAME_ID BIGINT,
	ARTICLE_TYPE_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (TEMPLATE_TYPE_ID) REFERENCES TEMPLATE_TYPE(ID),
	FOREIGN KEY (TEMPLATE_NAME_ID) REFERENCES TEMPLATE_NAME(ID),
	FOREIGN KEY (ARTICLE_TYPE_ID) REFERENCES ARTICLE_TYPE(ID)
);
----------- Create Tables ---------------

----------- Create Sequence ---------------
DROP SEQUENCE IF EXISTS ARTICLE_TYPE_SEQ
DROP SEQUENCE IF EXISTS FILE_DOWNLOAD_SEQ
DROP SEQUENCE IF EXISTS TEMPLATE_NAME_SEQ
DROP SEQUENCE IF EXISTS TEMPLATE_TYPE_SEQ

CREATE SEQUENCE ARTICLE_TYPE_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE FILE_DOWNLOAD_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE TEMPLATE_NAME_SEQ START WITH 1 INCREMENT BY 1
CREATE SEQUENCE TEMPLATE_TYPE_SEQ START WITH 1 INCREMENT BY 1
----------- Create Sequence ---------------












